// This file was generated by Prisma, and assumes you have installed the following:
import { defineConfig } from 'prisma/config'
import config from './src/app/config/index'

export default defineConfig({
  schema: 'prisma/schema',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: config.postgresql_database_url
  }
})
